[phases.setup]
nixPkgs = ["php83", "composer", "nodejs-20_x"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci --legacy-peer-deps",
  "npm run production"
]

[phases.build]
cmds = [
  "php artisan key:generate --force || true",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"

